# jekyll config 
# theme partly based: 
# Kiko-plus https://aweekj.github.io/Kiko-plus/ and Minima https://github.com/jekyll/minima

# basic
title: _drafts
description: digital rough frame carpentry, a blog of snippets and notes to get things started.
keywords: digital humanities, tutorial, snippets, code, linux
author: evanwill 

url: "https://evanwill.github.io/_drafts"

collections:
  notes:
    output: true

# Markdown
markdown: kramdown
kramdown:
  input: GFM
