# jekyll config 
# style partly based on K i k o - p l u s   https://aweekj.github.io/Kiko-plus/

# basic
title: _drafts
description: digital rough frame carpentry, a blog of snippets and notes to get things started.
keywords: digital humanities, tutorial, snippets, code, linux
author: evanwill 

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://evanwill.github.io/_drafts"

collections:
  notes:
    output: true

# Sass
# sass:
#  style: :compressed
#  sass_dir: _sass

# Markdown
markdown: kramdown
kramdown:
  input: GFM

