# Blog settings
permalink: /_drafts/:title

# My variables
title: _drafts
description: digital rough frame carpentry, a blog of snippets and notes to get things started.
keywords: digital humanities, tutorial, snippets, code, linux
google_verification: null


# File management
exclude: ["README.md"]

collections:
  notes:
    output: true

# Sass
sass:
  style: :compressed
  sass_dir: _sass


# Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
